# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCongen < Formula
  desc "Generates Go controller based on HTML"
  homepage "https://github.com/reddec/go-congen"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.6/go-congen_0.0.6_darwin_amd64.tar.gz"
      sha256 "1a568955f1604fcc3f61d651d65a2af0f967fb2bb1bcd97e8b83e63d973e2d44"
    end
    if Hardware::CPU.arm?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.6/go-congen_0.0.6_darwin_arm64.tar.gz"
      sha256 "82a6ca7af19207af5c3cd25cf62e1cc13a2ef92ffc195edf93e260e5e3d8b3e9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.6/go-congen_0.0.6_linux_amd64.tar.gz"
      sha256 "f63cfeccca3600047517b8939d928ee87614ac087cff476879765c9f440711f0"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.6/go-congen_0.0.6_linux_armv6.tar.gz"
      sha256 "f01bb197a1307e0a36b9ef35082c6103a06b9cc63b090cf5f18ba87f3d46ac93"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/go-congen/releases/download/v0.0.6/go-congen_0.0.6_linux_arm64.tar.gz"
      sha256 "474e6ce181c1eafa6dcfbf32b2e11fbfe35e276778b684182a8fb1960e3c2687"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "go-congen"
  end

  test do
    system "#{bin}/go-congen --help"
  end
end
