# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layout < Formula
  desc "Tool for creating new project from template"
  homepage "https://github.com/reddec/layout"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reddec/layout/releases/download/v1.3.0/layout_darwin_arm64.tar.gz"
      sha256 "592306da0244fb9ef002726ea70ee12890ce50a9dab918b768d9722e17873b53"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.0/layout_darwin_amd64.tar.gz"
      sha256 "05e2e0f37751042f75808ba38a50106039fd011cfb0157453bc59845796b7c41"

      def install
        bin.install "layout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.0/layout_linux_amd64.tar.gz"
      sha256 "d23028aac698b7939275c42e4c6454766b2d709f13f81d692044cc8ea10a06bc"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/layout/releases/download/v1.3.0/layout_linux_arm64.tar.gz"
      sha256 "1aef1edcfbcc8bd32da19c9917a6087bc055d1c3ee9613cabc8adeefef43ab38"

      def install
        bin.install "layout"
      end
    end
  end

  test do
    system "#{bin}/layout --help"
  end
end
