# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layout < Formula
  desc "Tool for creating new project from template"
  homepage "https://github.com/reddec/layout"
  version "1.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.2/layout_darwin_amd64.tar.gz"
      sha256 "70837a3356242b7bab60e5403c49dbe17fbc9d6049f1552ab8da57ac0b66a10d"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reddec/layout/releases/download/v1.3.2/layout_darwin_arm64.tar.gz"
      sha256 "b86f748a9cf997fedc5743ff417185e5aff313a5d99bf0b2f890818fef708148"

      def install
        bin.install "layout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/layout/releases/download/v1.3.2/layout_linux_arm64.tar.gz"
      sha256 "df1fdc383706a1e64fb0ed5b85e65960e518093aaf79a05b2d006f10c71aa5a6"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.2/layout_linux_amd64.tar.gz"
      sha256 "1fe59309a00a5ba7879ee0c213acf03fe2354eb5522b684f982e853f65f4dcaf"

      def install
        bin.install "layout"
      end
    end
  end

  test do
    system "#{bin}/layout --help"
  end
end
