# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Layout < Formula
  desc "Tool for creating new project from template"
  homepage "https://github.com/reddec/layout"
  version "1.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reddec/layout/releases/download/v1.3.3/layout_darwin_arm64.tar.gz"
      sha256 "b1bdf00cd7342a42e1475813467f9662efabca9917b4989388f90bb5c870b4e5"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.3/layout_darwin_amd64.tar.gz"
      sha256 "b15604012df26730c82c1ed5421d230155d1bb7fb751c2f4349cb296f226c659"

      def install
        bin.install "layout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/layout/releases/download/v1.3.3/layout_linux_arm64.tar.gz"
      sha256 "9beafbb7f5c8f7d7ba3cab6747a595e007ecde2496432908fb32456c0a0a5107"

      def install
        bin.install "layout"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/layout/releases/download/v1.3.3/layout_linux_amd64.tar.gz"
      sha256 "934c3f17fb7145a2e62034395820fd64db22d771c9078ee17e3a519baf384aec"

      def install
        bin.install "layout"
      end
    end
  end

  test do
    system "#{bin}/layout --help"
  end
end
