# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wd < Formula
  desc "Yet another webhook daemon"
  homepage "https://github.com/reddec/wd"
  version "0.0.9"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reddec/wd/releases/download/v0.0.9/wd_0.0.9_darwin_amd64.tar.gz"
      sha256 "695cbe9353af6ef365366a62f642243f93aefa16d6cdb2efbec03f2f67bc04be"
    end
    if Hardware::CPU.arm?
      url "https://github.com/reddec/wd/releases/download/v0.0.9/wd_0.0.9_darwin_arm64.tar.gz"
      sha256 "53d7e5670fed313d349250a9999dd7c4098e7d4346ba2aeb0d874d9621c31ae0"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/wd/releases/download/v0.0.9/wd_0.0.9_linux_armv6.tar.gz"
      sha256 "7db563a493c47711beeae168913020214ce225b4d65e54f33f53a5d22da8f480"
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/wd/releases/download/v0.0.9/wd_0.0.9_linux_amd64.tar.gz"
      sha256 "8eaaa497dab9f6cecb903e47b6f589cbac25de9b877b616378ea907e91809d36"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/wd/releases/download/v0.0.9/wd_0.0.9_linux_arm64.tar.gz"
      sha256 "4c0946cb32b3a2499d146dab33aca20cca99e775da74782a611184daf3226e46"
    end
  end

  def install
    bin.install "wd"
  end

  test do
    system "#{bin}/wd --help"
  end
end
