# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wd < Formula
  desc "Yet another webhook daemon"
  homepage "https://github.com/reddec/wd"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reddec/wd/releases/download/v0.1.0/wd_0.1.0_darwin_arm64.tar.gz"
      sha256 "6d208f63d03508050335dcdd88f41565d53961cd971174c08020d1daeef7f8a4"
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/wd/releases/download/v0.1.0/wd_0.1.0_darwin_amd64.tar.gz"
      sha256 "8e08d2acb278e419ec9193037db636945cf061534f307dbd7df017de6d0dc335"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/wd/releases/download/v0.1.0/wd_0.1.0_linux_armv6.tar.gz"
      sha256 "4aa50dbd6b040d46118790f0b7d659af3d2b4b60038b75cf1ee506a271dc3fbf"
    end
    if Hardware::CPU.intel?
      url "https://github.com/reddec/wd/releases/download/v0.1.0/wd_0.1.0_linux_amd64.tar.gz"
      sha256 "b4c88a734eb8d9586062cb6600a581749eaafc3188d27147b6975155e8a4bd96"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reddec/wd/releases/download/v0.1.0/wd_0.1.0_linux_arm64.tar.gz"
      sha256 "301bb49cdd24091ca77774ea8042e88e8b2ef5a37cff5e1ee156253ab151bf2f"
    end
  end

  def install
    bin.install "wd"
  end

  test do
    system "#{bin}/wd --help"
  end
end
